//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FrameWork_Manager_BaseManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FrameWork.Manager.BaseManager), typeof(System.Object));
		L.RegFunction("Init", Init);
		L.RegFunction("Destroy", Destroy);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FrameWork.Manager.BaseManager obj = (FrameWork.Manager.BaseManager)ToLua.CheckObject<FrameWork.Manager.BaseManager>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Destroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FrameWork.Manager.BaseManager obj = (FrameWork.Manager.BaseManager)ToLua.CheckObject<FrameWork.Manager.BaseManager>(L, 1);
			obj.Destroy();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

