//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameApp_ToLuaExpand_ObjectValueWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameApp.ToLuaExpand.ObjectValue), typeof(GameApp.ToLuaExpand.AbstractValue));
		L.RegFunction("New", _CreateGameApp_ToLuaExpand_ObjectValue);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("value", get_value, set_value);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGameApp_ToLuaExpand_ObjectValue(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				GameApp.ToLuaExpand.ObjectValue obj = new GameApp.ToLuaExpand.ObjectValue();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: GameApp.ToLuaExpand.ObjectValue.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_value(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameApp.ToLuaExpand.ObjectValue obj = (GameApp.ToLuaExpand.ObjectValue)o;
			UnityEngine.Object ret = obj.value;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index value on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_value(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameApp.ToLuaExpand.ObjectValue obj = (GameApp.ToLuaExpand.ObjectValue)o;
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 2);
			obj.value = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index value on a nil value");
		}
	}
}

