//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameApp_ToLuaExpand_BindableValueWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameApp.ToLuaExpand.BindableValue), typeof(System.Object));
		L.RegFunction("New", _CreateGameApp_ToLuaExpand_BindableValue);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("wraps", get_wraps, set_wraps);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGameApp_ToLuaExpand_BindableValue(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				GameApp.ToLuaExpand.BindableValue obj = new GameApp.ToLuaExpand.BindableValue();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: GameApp.ToLuaExpand.BindableValue.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_wraps(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameApp.ToLuaExpand.BindableValue obj = (GameApp.ToLuaExpand.BindableValue)o;
			System.Collections.Generic.List<GameApp.ToLuaExpand.ValueWrap> ret = obj.wraps;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index wraps on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_wraps(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameApp.ToLuaExpand.BindableValue obj = (GameApp.ToLuaExpand.BindableValue)o;
			System.Collections.Generic.List<GameApp.ToLuaExpand.ValueWrap> arg0 = (System.Collections.Generic.List<GameApp.ToLuaExpand.ValueWrap>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<GameApp.ToLuaExpand.ValueWrap>));
			obj.wraps = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index wraps on a nil value");
		}
	}
}

