//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Utility_Singleton_FrameWork_AppFacadeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Utility.Singleton<FrameWork.AppFacade>), typeof(System.Object), "Singleton_FrameWork_AppFacade");
		L.RegFunction("New", _CreateUtility_Singleton_FrameWork_AppFacade);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUtility_Singleton_FrameWork_AppFacade(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Utility.Singleton<FrameWork.AppFacade> obj = new Utility.Singleton<FrameWork.AppFacade>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Utility.Singleton<FrameWork.AppFacade>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Utility.Singleton<FrameWork.AppFacade>.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

